// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzEIt8fs10wW0gEy_oL2t5yuVRYnvz3jw',
    appId: '1:847603438626:web:8547bd63d296b371bda67b',
    messagingSenderId: '847603438626',
    projectId: 'toss-coin-47fca',
    authDomain: 'toss-coin-47fca.firebaseapp.com',
    storageBucket: 'toss-coin-47fca.appspot.com',
    measurementId: 'G-SVNTT0QQTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYfRni9HH8x3tPuyLFuKaadkSEdR_0Q_Q',
    appId: '1:847603438626:android:7a692c6f9afff1f4bda67b',
    messagingSenderId: '847603438626',
    projectId: 'toss-coin-47fca',
    storageBucket: 'toss-coin-47fca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBATheO5X4LmKehyXvdhpj1MsLMmgeKiQU',
    appId: '1:847603438626:ios:478c8f65a18a3b4abda67b',
    messagingSenderId: '847603438626',
    projectId: 'toss-coin-47fca',
    storageBucket: 'toss-coin-47fca.appspot.com',
    iosBundleId: 'com.example.coinFlip',
  );
}
